### ISSUE TITLE
Vademecum: CI/CD? Adottare nuovo standard?

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/CommunityIssueTracker#104]
Siamo nel 2021, e il vademecum é sempre una gran bella trovata promozionale.
Tuttavia, è un po' obsoleto il metodo di aggiornamento.
Non che Github non vada bene, ma diventa problematico non solo aggiornare il contenuto, ma anche avere una versione "già bella e pronta" del vademecum perché poi ogni volta deve essere scaricato "compilato" e "ricomittato" a mano.

Le scelte sono due:
- **settare una CI / CD,** ossia, **script** che costruiscano il vademecum al posto nostro, che non risolverebbe però il problema dell'aggiornamento
- rifare tutto in un **formato open** (Markdown ad esempio) in modo tale non solo da facilitare l'aggiornamento ma non avere il problema del rendering

Personalmente preferirei la seconda + diversi branches, in modo tale da non avere tutto nella stessa cartella, ma bisognerebbe organizzare un attimo il lavoro e definire come dobbiamo procedere.

EDIT: poi tanto comunque questo issue serve per capire cosa fare, andrà fatto un issue a parte nella repo del vademecum

**Comment by Mte90** [comment]
La CI/CD può committare sul repo quindi basta decidere se mgirare ad altre soluzioni o fare la CI/CD che aggiorna il repo https://github.com/MozillaItalia/firefox-vademecum

Oppure fare delle release di github. Ci sono varie opzioni dobbiamo deciderci.

**Comment by dag7dev** [comment]
> 
> 
> La CI/CD può committare sul repo quindi basta decidere se mgirare ad altre soluzioni o fare la CI/CD che aggiorna il repo https://github.com/MozillaItalia/firefox-vademecum
> 
> Oppure fare delle release di github. Ci sono varie opzioni dobbiamo deciderci.

esatto, le release di github sono molto comode, e se non sbaglio sono settabili direttamente da GH Actions

possiamo volendo fare tre branches per le varie versioni e poi settare un unico workflow che produca quelle versioni, sempre se decidiamo di avere tre versioni e di non accorpare tutto
