### ISSUE TITLE
Riorganizzazione gruppi Telegram - DEM e Dev2.0

### ISSUE THREAD

**Issue by dag7dev** [MozillaItalia/CommunityIssueTracker#105]
# Riorganizzazione gruppi Telegram - DEM e Dev2.0

## Situazione attuale
Abbiamo i seguenti gruppi:
- Home
- Dev
- Design
- Marketing
- L10N

### Problemi
- Il gruppo Dev per un bug di Telegram è assaltato da utenti spam che ci fanno perdere tempo.
  Il problema è irrisolvibile e la situazione é diventata davvero fastidiosa.
- I gruppi Marketing e Design sono quasi sempre silenziosi: essendoci poca attività non solo possono essere accorpati ma possono anche lavorare a stretto contatto. 

## Proposta di modifica
- Home --> sempre Home, ma specifichiamo nella desc che si parla anche di tecnologie, soluzioni e progetti Open Source 
- Developers --> Dev vecchio
- Design & Marketing --> accorpa Marketing e Design

### Come
**24 agosto:**
- i gruppi Dev, e Design verranno messi in sola lettura.
- il gruppo Marketing cambierà dicitura in "Mozilla Italia - Design & Marketing" e nella descrizione, un ibrido tra la descrizione
di marketing e quella di design, comunque rendendo evidente la fusione tra i due.

**24 settembre:**
- i gruppi Dev e Design vengono eliminati e tutte le eventuali persone rimaste verranno cancellate

**25 settembre:**
~~- termine aggiornamento link di MozItaBot  (Developers e Marketing & Design)~~ **già fatto, vedi 

## Conclusione
Abbiamo infine, al 31.08.2021 questi gruppi:
- Home
- Dev
- Design & Marketing
- L10N

(vedere https://github.com/MozillaItalia/mozitahub_bot/commit/03d367c8b2210515ad03769dff0959dd78315a23)

**Comment by Mte90** [comment]
finito :-)
