### ISSUE TITLE
Gmail FSAItaly

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#12]
Define a strategy for the fsaitaly@gmail.com account.
Definire una strategia per l'account Email fsaitaly@gmail.com

**Comment by Mte90** [comment]
Maybe we can forward all the email to mozitalian one

**Comment by Mte90** [comment]
Any updates on this one?

**Comment by Mte90** [comment]
Seems that in the folder of this account on gdrive I don't have anymore the read/write permissions
