### ISSUE TITLE
WebVR Summer Fest

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#20]
Evento Estivo in Spiaggia sulla WebVR 

Summer Event on the beach for the WebVR

**Comment by edovio** [comment]
* [ ]   Luogo sulla spiaggia dove ospitare l'evento
* [ ]  Data dell'evento
* [ ]  Determinare il format
* [ ]  Creare Codice di Condotta
* [ ]  Speaker da invitare
* [ ]  Creare Grafiche
* [ ]  Creare comunicati Stampa
* [ ]  Contattare le testate giornalistiche online e/o offline
* [ ]  Valutare se creare Ticket o no
* [ ]  Produrre e/o richiedere le presentazioni
* [x] Traduzione dell'etherpad - https://public.etherpad-mozilla.org/p/mozSummerParty

on English:
* [ ]   Place on the beach where host the event
* [ ]  Date of the Event
* [ ]  Event Format
* [ ]  Make a Code of Conduit
* [ ]  Invite Speakers
* [ ]  Create Graphics Designs
* [ ]  Create Press releases
* [ ]  Contact Online & Offline Newspaper
* [ ]  Evaluate if create Tickets or not
* [ ]  Make and/or ask the slide decks 
* [x] Translate the etherpad - https://public.etherpad-mozilla.org/p/mozSummerParty

**Comment by edovio** [comment]
Richiesta al [Sax Beach](https://www.google.it/maps/uv?hl=en&pb=!1s0x12e0cb4b591a9313:0x67f6e22590776897!2m19!2m2!1i80!2i80!3m1!2i20!16m13!1b1!2m2!1m1!1e1!2m2!1m1!1e3!2m2!1m1!1e5!2m2!1m1!1e4!3m1!7e115!4shttps://picasaweb.google.com/lh/sredir?uname%3D112002764369919627221%26id%3D6412952254734130178%26target%3DPHOTO!5ssax+beach+quartu+-+Google+Search&imagekey=!1e3!2s-HAmql7MqFwc/WP9iGTD33AI/AAAAAAAAcuQ/hiS_4QmJrNAlt6evcE1T1j4f_gm0fPyFwCLIB&sa=X&ved=0ahUKEwiL-ePsp_LTAhXJPBoKHci3CkkQoioIggEwDg) Disponibilità ad hostare l'evento.

Requested availability to host the event at [Sax Beach](https://www.google.it/maps/uv?hl=en&pb=!1s0x12e0cb4b591a9313:0x67f6e22590776897!2m19!2m2!1i80!2i80!3m1!2i20!16m13!1b1!2m2!1m1!1e1!2m2!1m1!1e3!2m2!1m1!1e5!2m2!1m1!1e4!3m1!7e115!4shttps://picasaweb.google.com/lh/sredir?uname%3D112002764369919627221%26id%3D6412952254734130178%26target%3DPHOTO!5ssax+beach+quartu+-+Google+Search&imagekey=!1e3!2s-HAmql7MqFwc/WP9iGTD33AI/AAAAAAAAcuQ/hiS_4QmJrNAlt6evcE1T1j4f_gm0fPyFwCLIB&sa=X&ved=0ahUKEwiL-ePsp_LTAhXJPBoKHci3CkkQoioIggEwDg)

**Comment by Mte90** [comment]
I think that actually that events is changing without my presence

**Comment by edovio** [comment]
The Event Was close because we don't have the availabity of the host. I will plan in the next days a WebVR meetup here in Cagliari
