### ISSUE TITLE
Mozilla Italia l10n Guide Articolo

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/CommunityIssueTracker#43]
- [x] Rispondere alla email https://public.etherpad-mozilla.org/p/mozita-articolo-guida-l10n
- [x] Revisionare testo articolo
- [x] Immagini per l'articolo
- [x] Revisionare articolo dalla comunità
- [x] Pubblicare articolo

**Comment by kitsunenosaraT** [comment]
@Mte90 grazie per l'aiuto 😀 
Per quanto riguarda i numerosi link che ho messo, possiamo ancorarli invece di lasciarli "nudi" nel testo? es. `<a href="URL">nome pagina</a>`

Inoltre io ho visto che l'intervista veniva lunghetta, quindi non ho risposto alle domande più generiche. Ma se pensi che sia utile, basta che me lo dici e faccio anche quelle.

**Comment by Mte90** [comment]
Prima revisione fatta, vediamo di rispondere alle prime domande del documento e poi di proseguire con gli altri punti

**Comment by kitsunenosaraT** [comment]
Quando vuoi ho risposto anche alle prime domande, tranne una per cui sto ancora cercando un esempio illuminante…

**Comment by kitsunenosaraT** [comment]
Ciao, ho appena risposto all'ultima domanda in sospeso.
Che il QA abbia inizio! :D

**Comment by Mte90** [comment]
Rimane da condividire l'articolo sul forum per qa e pubblicazione

**Comment by kitsunenosaraT** [comment]
Articolo condiviso sul [forum](https://forum.mozillaitalia.org/index.php?topic=56824.new#new)

**Comment by kitsunenosaraT** [comment]
Articolo revisionato, già formattato per Wordpress [qui](https://github.com/flodolo/Mozilla-Italia-l10n-guide/blob/0805ef68f8351198665343e2a234f3f2d0761d4d/resources/intervista.md)
@Mte90 , ci dai l'ok?

**Comment by Mte90** [comment]
Cosi mi fate sentire importante ma mi sembra ottima ora :-D
Per me si può pubblicare ma le domande vanno messe in grassetto in modo da evidenziare le varie sezioni.

**Comment by kitsunenosaraT** [comment]
🎉 [Articolo pubblicato!](https://blog.mozilla.org/press-it/2017/05/30/la-guida-di-localizzazione-di-mozilla-italia-al-mozilla-global-sprint/)
Mi sono presa la libertà di inserire una breve introduzione al Global Sprint citando i progetti di @edovio e @ruphy (noi open leader italiani dobbiamo restare uniti 😉 )

**Comment by Mte90** [comment]
Uh me lo aspettavo sul sito di Mozilla Italia nel blog ma va bene lo stesso :-)

**Comment by kitsunenosaraT** [comment]
Errore mio 😞 
Adesso è sul blog giusto: 
https://www.mozillaitalia.org/home/2017/05/30/la-guida-di-localizzazione-di-mozilla-italia-al-mozilla-global-sprint/

**Comment by Mte90** [comment]
Per punizione dovrai scrivere 100 volte sulla lavagna le regole più importanti per la traduzione!!!
