### ISSUE TITLE
Create a Project in this Repo for the new Website

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#48]
Create a new Project in this repo to track and follow the status of the creation of a new possible website for Mozilla Italia

**Comment by edovio** [comment]
Creare un nuovo progetto in questo repository per tenere traccia e seguire lo stato e gli sviluppi di un nuovo possibile website per Mozilla Italia

**Comment by EugenioPetulla** [comment]
Il repo ufficiale poi ci sarebbe anche ma andrebbe unito e allineato al mio: https://github.com/MozillaItalia/mozillaitalia.github.io

**Comment by edovio** [comment]
Si ho visto il tuo repo, la mia idea era di creare un tracker specifico per il progetto sito in cui discutere su contenuti ed in genere come elemento aggregante della community (Developer, Localizzatori, Participation in genere ecc ecc), questo in modo tale da non sporcare quello implementativo dove magari si discute più sulle scelte tecniche di sviluppo :)

**Comment by Mte90** [comment]
Direi di fare una nuova label specifica e poi ognuno sulla kanban personale si segna le cose da fare, cosi evitiamo confusione e specifichiamo che sul repo del progetto c'è la parte tech mentre qui il brainstorming e testo.

**Comment by edovio** [comment]
Inizialmente pensavo anche io questo però poi ho riflettuto meglio e credo che invece possa essere utile perchè, questa attivitàm non è solo mia e tua o di Eugenio e Gabriele ma se si fa un sito deve essere rappresentativo di tutta la comunità e dunque penso sia importante che ci sia un progetto specifico per questo dove chiunque possa dare un suo punto di vista.

**Comment by Mte90** [comment]
Uhm forse potremmo spostare il repo di eugenio dentro l'organizzazione mozilla italia sul repo mozillaitalia.github.io ufficiale, cosi facciamo la roba tecnica e poi facciamo la kanban dove siamo tutti.
Volevo evitare di mettere ticket su più kanban che ci confondiamo :-/

**Comment by edovio** [comment]
infatti quelle del sito andrebbe a finire li e non nel mio e nel tuo xD

**Comment by edovio** [comment]
tanto poi sappiamo che stiamo lavorando ad un sito xD

**Comment by EugenioPetulla** [comment]
Ditemi cosa fare e lo faccio, anche una Pull Request volendo, basta che @Mte90 apre il ramo gh-pages poi io faccio pull direttamente su quello e teniamo tutto sotto al cappello Mozilla, poi saro' io a occuparmi di forkare il repo e di fare pull dopo le modifiche, no problem. :)
