### ISSUE TITLE
OpenStudentBook Articolo

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/CommunityIssueTracker#50]
- [x] Preparare etherpad https://public.etherpad-mozilla.org/p/mozita-articolo-osb
- [x] Revisionare testo articolo
- [x] Revisionare articolo dalla comunità
- [ ] Immagini per l'articolo
- [ ] Pubblicare articolo

**Comment by Mte90** [comment]
ping for @edovio

**Comment by edovio** [comment]
Is not a priority make an article about this project now. 
Publish two article in few days could scatter the attention in other projects involved at the Global Sprint. 
We can think to reschedule it after the Global Sprint. In this way we can try to collect the max attention for the L10n Guide Article and for the OpenStudentBook :)

**Comment by Mte90** [comment]
Ok! Lower priority good to know :-)

**Comment by edovio** [comment]
ping for @Mte90 (When return from AllHands!)

**Comment by Mte90** [comment]
There few comments in the etherpad and I think that is required a revision from others, we can ask in the forum.

**Comment by Mte90** [comment]
We have to work on that, the summer helped us to forget this activity XD

**Comment by Mte90** [comment]
Review from community done, we need to confirm for publish

**Comment by Mte90** [comment]
Spostato coem task su un altro repo dedicato :-)
