### ISSUE TITLE
Firefox Nightly Campaign

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#54]
Create a National Campaign for promote the usage of Firefox Nightly
* [x] Define a period: 2 weeks before Linux day 10-28/10/2017
* [ ] Create a Draft Doc
* [ ] Define a Team
* [ ] Define Graphics
* [ ] Write a Proposal 
* [ ] Write the Campaign in the Mozilla Wiki

Creare una Campagna nazionale per promuovere l'utilizzo di Firefox Nightly
* [x] Definire a period: 2 settimane prima del Linux day 10-28/10/2017
* [ ] Creare una Bozza in un Documento
* [ ] Definire un Team
* [ ] Definire Materiale Grafico
* [ ] Inserire la Campagna nel Wiki Mozilla
* [ ] Scrivere una proposta

**Comment by Mte90** [comment]
After a chat with @pascalchevrel we will continue with our plan but:

- Create graphical poster to promote nightly to sent to lug and other type of clubs in the country
- Create 2 kind of slides: one about Firefox nightly with features (like containers) and one about QA to use for our specific events
- Publish on about:home for italians messages about events on nightly

We need to work on gather new people for waulity and not only quantity. People that want to join discussion on telegram or irc and open tickets
