### ISSUE TITLE
Reps Call Mensile

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#74]
Organizzazione della Call Mensile dei Reps Italiani

**Comment by edovio** [comment]
Agenda Meeting: https://docs.google.com/document/d/1w4vY-TWAmIwp-pjPEBEKP7FUVYFN9SOg5jXjrJeO7Ug/edit

**Comment by edovio** [comment]
Call per il mese di Giugno: 11/06/2020

**Comment by edovio** [comment]
Call per il mese di Luglio: 18/07/2020

**Comment by edovio** [comment]
Call per il mese di Agosto: **Vacanza** 
Per urgenze ci sentiamo su Telegram

**Comment by Mte90** [comment]
Dobbiamo organizzare l'incontro di novembre dove faremo:

* Analisi Linux Day
* Pianificazione per il futuro con verifica disponibilità

**Comment by dag7dev** [comment]
Call mensile di novembre: fatta!

**Comment by Mte90** [comment]
Abbiamo migrato i resoconti su discourse https://discourse.mozilla.org/t/resoconto-call-reps/71645
