### ISSUE TITLE
Prossimi Speakers and Debate su IHR

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#75]

**Comment by edovio** [comment]
*Primo Dibattito*

- ***Possibile argomento di attualità da proporre:***
- [ ] Privacy and Security: App di Tracking per COVID

- ***Possibili altre community Italiane da coinvolgere:***
- [ ] LibreItalia
- [ ] Wikimedia Italia

- ***Settimane possibili dove organizzare il dibattito:***

- [ ] 2° Settimana di Giugno
- [ ] 3° Settimana di Giugno
- [ ] 4° Settimana di Giugno
- [ ] 1° Settimana di Luglio

**Comment by edovio** [comment]
Ragazzi abbiamo qualche altre idea di community da coinvolgere?

**Comment by Mte90** [comment]
Forse https://www.hermescenter.org/ anche se non è una comunità OSS nel senso pieno.
Si può coinvolgere https://www.statigeneralinnovazione.it/online/appuntamento-per-il-19-febbraio-2020-2si-per-regioni-e-comuni/ alcuni di questo progetto tipo la Marzano, io ed Enio eravamo quelli che seguivano il tavolo su opensource.

**Comment by edovio** [comment]
Primo Evento previsto per 8 Luglio 2020 ore 18.30.
