### ISSUE TITLE
Promozione della Localizzazione

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#77]
Idee per la promozione della localizzazione

**Comment by Mte90** [comment]
Un riferimento di esempio https://www.youtube.com/user/wikimediaitalia/videos

**Comment by edovio** [comment]
Idee:

Creare una gara tipo Hackaton con dei premi e delle frasi da localizzare per presentare l'attività e aiutare le persone a conoscere la localizzazione

**Comment by astrastefania** [comment]
Idea di possibile talk/serata: 

- intro iniziale sull on-boarding 
- screen sharing mentre una persona traduce una stringa
- una seconda parte screen sharing del processo di validazione
- Q/A e condivisioni
