### ISSUE TITLE
Sprint su Common Voice

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#78]
- Mini-talk introduttivo su Common Voice e DeepSpeech
- sprint di Common Voice con countdown
- Q/A e condivisioni
- sprint su Common Voice con countdown
- condivisioni e saluti

**Comment by xplosionmind** [comment]
È già stato fatto o è in programma?

**Comment by Mte90** [comment]
No è una idea ma forse già sarà per il prossimo che facciamo domenica (ne abbiamo parlato alla riunione del mese attuale)

**Comment by xplosionmind** [comment]
Me l’ero perso. Ottimo, grazie!

**Comment by dag7dev** [comment]
Aggiornamento: previsto sprint 3 Novembre di @astrastefania

**Comment by dag7dev** [comment]
Sprint CV fatto il 3/11 tenuto da @astrastefania me e @Sav22999 
Inviati adesivi a coloro che li hanno richiesti
