### ISSUE TITLE
Presenza LinuxDay Online 2020

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/CommunityIssueTracker#84]
Dobbiamo definire gli argomenti per cui partecipare alla CFP nazionale https://www.linuxday.it/2020/partecipa/

Abbiamo per il momento:

* @dag7dev per (solo) Common Voice (le solite slide) - **APPLICATO**
* <s>@mone27 per Mozilla IoT e scrivere una webthing in rust</s>
* @Sav22999 riguardo Mozilla L10n - **APPLICATO**
* @xplosionmind riguardo MDN - **APPLICATO**
* @gabrycaos riguardo Accessibilità - **APPLICATO**
* @astrastefania su DeepSpeech - **APPLICATO** 
* <s>@edovio su Internet Health Report - **APPLICATO**</s>
* @dexterp37 Firefox telemetry e il caso Italia durante il lockdown - **APPLICATO**
* @eugeniopetulla Firefox DevTools - **APPLICATO**

Argomenti da trovare il relatore per applicare:

* WebExtensions

Da fare:

* Invio solita email con link presentazioni per i lug che faranno dal vivo
* Verificare se hanno applicato i vari relatori
* Verificare se serve aiuto nella revisione delle slide

**Comment by mone27** [comment]
Io pensavo: Mozilla IoT e scrivere una webthing in rust

**Comment by xplosionmind** [comment]
Ciao, io parlerei volentieri di MDN. Ho tradotto già alcuni articoli e lo visito tutti i giorni... Se credete abbia sufficiente esperienza, me ne occuperei con piacere.

Tuttavia, l’unico problema è che io con forte probabilità non riuscirò ad esserci quel weekend. A quanto ho letto, però, si può fare una registrazione o connettersi online, dunque ce la farei tranquillamente.

**Comment by Mte90** [comment]
Ti segno, quando applichi vedi di spiegarlo nel campo apposito così ne tengono conto.

**Comment by xplosionmind** [comment]
Grazie. Quindi scelgo tutto io, sia titolo che descrizione?

Ovviamente dovrò inserire che partecipo come membro di Mozilla Italia

**Comment by Mte90** [comment]
Si esatto, poi per le slide ti diamo una mano e le vediamo insieme via telegram. Anche per strutturare il talk.

**Comment by xplosionmind** [comment]
Perfetto. Grazie!

**Comment by xplosionmind** [comment]
Ho creato [questo etherpad](https://etherpad.wikimedia.org/p/Mozilla_Talk_for_MDN_at_Linux_Day_2020) per strutturare il talk

**Comment by dag7dev** [comment]
Abstract scritto, titolo scritto, application fatta!

**Comment by EugenioPetulla** [comment]
Ok, vedo di rimediare un titolo e un abstract decente e applico entro la prossima settimana per i devtools.

**Comment by edovio** [comment]
Ho applicato con un Talk sull'Internet Health Report

**Comment by EugenioPetulla** [comment]
@Mte90 ho applicato anche io con i dev tools

**Comment by dag7dev** [comment]
Tutti: video.linux.it
Common Voice: https://www.youtube.com/watch?v=mdunfPliNgQ
Localizzazione: https://www.youtube.com/watch?v=WN8uJCdhPqg
