### ISSUE TITLE
Calendario Eventi 2020

### ISSUE THREAD

**Issue by edovio** [MozillaItalia/CommunityIssueTracker#85]

**Comment by edovio** [comment]
Calendario:

* [ ] **WK 25**: 
**Common voice Monthly Sprint** - Lunedì 15 Giugno alle ore 18.30 
**RustOnline: Gruppo di Studio RUST** - 18 Giugno ore 16.30 - Rust Italia (Torino) 
Referente: @astrastefania 

* [ ] **WK 26**:
 **ANNULLATO** 


* [ ] **WK 27**:
**Call Mensile Mozilla Italia** - Venerdì 03 Luglio ore 18.30
 Referente @Sav22999 

* [ ] **WK 28**:
**IHR:  Dibattito Pubblico IHR** - Mercoledì 08 Luglio ore 18.30 
Referente @edovio 

* [ ] **WK 29**: 
**Mozilla Italian Reps Monthly Call** (Da definire) 
Referente @edovio 
**RustOnline:** (Evento da definire) - Giovedì 16 Luglio ore 18.30 - Rust Italia (Torino)
Referente: @astrastefania 

* [ ] **WK 30**:
**Maratona Common Voice Italia di Luglio** - Mercoledì 22 Luglio ore 18.30
 Referente: @astrastefania

**Comment by edovio** [comment]
* [x] **WK 31** (Dal 27 Luglio al 2 Agosto) :
**VACANZA**

* [x] **WK 32** (Dal 3 Agosto al 9 Agosto):
**CALL MENSILE NAZIONALE**
 Referente: @Sav22999 

* [x] **WK 33** (Dal 10 Agosto al 16 Agosto):
**VACANZA**

* [x] **WK 34** (Dal 17 Agosto al 23 Agosto):
**VACANZA**

* [x] **WK 35** (Dal 24 Agosto al 30 Agosto):
**VACANZA**

* [x] **WK 36** (Dal 31 Agosto al 06 Settembre):
**CALL MENSILE NAZIONALE**
 Referente:  @Sav22999 

* [ ] **WK 37** (Dal 07 Settembre al 13 Settembre):
**MozAperitivo Online su Hub** (07 Settembre ore 18.30) 
 Referente: @edovio 

* [x] **WK 38** (Dal 14 Settembre al 20 Settembre):
**Talk su about:config**
 Referente: @Mte90 

* [ ] **WK 39** (Dal 21 Settembre al 27 Settembre):
**Common Voice Sprint** 
 Referente: @astrastefania @Sav22999 

* [ ] **WK 40** (Dal 28 Settembre al 04 Ottobre):
**CALL MENSILE NAZIONALE**
 Referente:  @Sav22999 

* [ ] **WK 41** (Dal 05 Ottobre al 11 Ottobre):
**IHR School 2020** (Giovedì 07 Ottobre 2020 Ore 18.30) ANNULLATO
 Referente: @edovio 

* [ ] **WK 42** (Dal 12 Ottobre al 18 Ottobre):
**Lab su Estensioni in Firefox** ANNULLATO
 Referente: @Mte90 @Sav22999 

* [x] **WK 43** (Dal 19 Ottobre al 25 Ottobre):
**Linux Day 2020 (Sab 24 e Dom 25 Ottobre)**
 Referente: @Mte90 @astrastefania 

* [ ] **WK 44** (Dal 26 Ottobre al 01 Novembre):
**Common Voice Sprint**
 Referente: @astrastefania @Sav22999 

* [ ] **WK 45** (Dal 02 Novembre al 8 Novembre):
**CALL MENSILE NAZIONALE**
 Referente:  @Sav22999 

* [ ] **WK 46** (Dal 09 Novembre al 15 Novembre):
**Evento
 Referente: 

* [ ] **WK 47** (Dal 16 Novembre al 22 Novembre):
**Evento
 Referente: 

* [ ] **WK 48** (Dal 23 Novembre al 29 Novembre):
**Evento
 Referente: 

* [ ] **WK 49** (Dal 30 Novembre al 06 Dicembre):
**Evento
 Referente: 

* [ ] **WK 50** (Dal 07 Dicembre al 13 Dicembre):
**Evento
 Referente: 

* [ ] **WK 51** (Dal 14 Dicembre al 20 Dicembre):
**Evento
 Referente: 

* [ ] **WK 52** (Dal 21 Dicembre al 27 Dicembre):
**Evento
 Referente: 

* [ ] **WK 53** (Dal 28 Dicembre al 03 Gennaio):
**Evento
 Referente:

**Comment by dag7dev** [comment]
WK 45 (Dal 02 Novembre al 8 Novembre):
CALL MENSILE NAZIONALE

Ho svolto io la call!
