### ISSUE TITLE
Creazione di un gruppo di Social Media Marketing

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/CommunityIssueTracker#88]
Cercare anche dei membri che siano attivi sui social e sappiano fare dei post accattivanti (ovviamente il processo di revisione c'è sempre).

Propongo Damiano a questo proposito

**Comment by xplosionmind** [comment]
Appena finita la sessione (ufff) io volentieri posso dare una mano!

**Comment by Mte90** [comment]
# Resoconto 13/07/2020

Lo scopo del team è quello di dare una mano alla comunità nella creazione di contenuti testuali per i nostri social attuali FB/TW. Un domani che il gruppo si struttura meglio possiamo valutare anche altri che richiedono anche più attenzione come Instagram che richiede anche un lavoro grafico.  
Ad oggi il flusso richiede una revisione quindi sfruttando un documento come https://docs.google.com/spreadsheets/d/1GYPYUwi0HVgpy-vh8S0Klzkf_GviX6eqqxt3eSkanpg/edit#gid=0 possiamo semplificare la procedura.
Si può prendere idea da social di altri progetti come Wikimedia e LibreOffice o https://twitter.com/MozillaZineFr che sono molto attivi che fanno anche video.

* https://docs.google.com/document/d/1j5LJsHGQZ4EDfHbQoJWs_P7yChZcAVp10DFHfP6VZBw/edit#heading=h.rni30fdjfvun
* https://docs.google.com/document/d/1oRaA7xBYwfewUiafh-4vvg27idx-RPF5KBKJY4y-PoI/edit

Per i video l'idea è di avere un pilota definitivo per settembre così nel frattempo raccogliamo idee e revisioniamo, visto il periodo estivo.

Siamo d'accordo che:

* Per gli eventi dobbiamo avere i testi prima di una settimana e sapere quando ci sono
* Provare con testi e video per capire che prove di materiale e argomenti vogliamo sperimentare e capire gli utenti che ci seguono e cosa funziona
* Condividere materiale trovato su internet (anche in inglese) che potrebbe essere interessante sul gruppo, così poi facciamo i testi e poli mandiamo in revisione
* I testi per il momento sul gruppo marketing per una questione di praticità

**Comment by Mte90** [comment]
# Flusso

- qualcuno pubblica il link sul gruppo telegram
- persona dice "ci penso io!"
- tizio scrive i testi per i social con hashtag sotto i 240 caratteri con link o foto
- @Mte90 manda per la revisione
- revisione ok, si pubblica sui vari social

**Comment by xplosionmind** [comment]
> # Flusso

Diamoci questa possibilità. Direi che possiamo farcela!
