### ISSUE TITLE
Creare in anticipo tutti gli eventi di Mozilla Italia

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/CommunityIssueTracker#90]
Così che la gente possa organizzarsi con dovuto anticipo. Gli eventi, ovviamente, inserirli tutti in un unico posto: Community Portal > Mozilla Italia > Eventi

**Comment by edovio** [comment]
Questo è utile e corretto ma finchè il sistema di revisione risulta abbastanza lungo (ricordiamoci che siamo volontari e non lavoriamo per Mozilla Italia)  i tempi di produzione e di pubblicazione devono essere abbastanza prolungati. 
Personalmente ritengo che in questa ottica bisogna definire in largo anticipo (2 o 3 mesi prima gli eventi), così da poter produrre in un mese il materiale grafico e promozionale e poter calendarizzare con un giusto anticipo anche gli eventi sul Community Portal

**Comment by edovio** [comment]
Discusso e approvato nella Call dei Reps del 18 Luglio. Verrà fatta una programmazione su base trimestrale delle attività, pianificando nel community Portal un mensilmente gli eventi. 

Voti a Favore: 5 , Voti contrari: 0
